"""Initial schema

Revision ID: 2d5ebbd852e5
Revises: 
Create Date: 2026-09-17 13:33:52.000062
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d5ebbd852e5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    op.create_table('conversations',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_user_created', 'conversations', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_index('ix_conversations_user_status', 'conversations', ['user_id', 'status'], unique=False)
    op.create_table('knowledge_bases',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_bases_slug'), 'knowledge_bases', ['slug'], unique=True)
    op.create_index('ix_knowledge_bases_status', 'knowledge_bases', ['status'], unique=False)
    op.create_table('documents',
    sa.Column('knowledge_base_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_version_id'], ['document_versions.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_kb_status', 'documents', ['knowledge_base_id', 'status'], unique=False)
    op.create_index('ix_documents_status', 'documents', ['status'], unique=False)
    op.create_table('llm_usage',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_usage_conversation', 'llm_usage', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_llm_usage_created', 'llm_usage', ['created_at'], unique=False)
    op.create_index('ix_llm_usage_provider_model', 'llm_usage', ['provider', 'model'], unique=False)
    op.create_index(op.f('ix_llm_usage_request_id'), 'llm_usage', ['request_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_table('document_versions',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=128), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('embedding_provider', sa.String(length=100), nullable=True),
    sa.Column('embedding_model', sa.String(length=200), nullable=True),
    sa.Column('embedding_dimension', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version_number', name='uq_doc_version')
    )
    op.create_index('ix_doc_versions_doc_status', 'document_versions', ['document_id', 'status'], unique=False)
    op.create_index('ix_doc_versions_hash', 'document_versions', ['file_hash'], unique=False)
    op.create_table('support_feedback',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_created', 'support_feedback', ['created_at'], unique=False)
    op.create_index('ix_feedback_message', 'support_feedback', ['message_id'], unique=False)
    op.create_index('ix_feedback_user', 'support_feedback', ['user_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=500), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_version_id', 'chunk_index', name='uq_chunk_version_index')
    )
    op.create_index('ix_chunks_page', 'document_chunks', ['page_number'], unique=False)
    op.create_index('ix_chunks_version', 'document_chunks', ['document_version_id'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingestion_jobs_document', 'ingestion_jobs', ['document_id'], unique=False)
    op.create_index('ix_ingestion_jobs_status_created', 'ingestion_jobs', ['status', 'created_at'], unique=False)
    op.create_table('retrieval_logs',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('rerank_score', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_retrieval_logs_conversation', 'retrieval_logs', ['conversation_id'], unique=False)
    op.create_index('ix_retrieval_logs_created', 'retrieval_logs', ['created_at'], unique=False)
    op.create_index('ix_retrieval_logs_request', 'retrieval_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_retrieval_logs_request_id'), 'retrieval_logs', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retrieval_logs_request_id'), table_name='retrieval_logs')
    op.drop_index('ix_retrieval_logs_request', table_name='retrieval_logs')
    op.drop_index('ix_retrieval_logs_created', table_name='retrieval_logs')
    op.drop_index('ix_retrieval_logs_conversation', table_name='retrieval_logs')
    op.drop_table('retrieval_logs')
    op.drop_index('ix_ingestion_jobs_status_created', table_name='ingestion_jobs')
    op.drop_index('ix_ingestion_jobs_document', table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index('ix_chunks_version', table_name='document_chunks')
    op.drop_index('ix_chunks_page', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index('ix_feedback_user', table_name='support_feedback')
    op.drop_index('ix_feedback_message', table_name='support_feedback')
    op.drop_index('ix_feedback_created', table_name='support_feedback')
    op.drop_table('support_feedback')
    op.drop_index('ix_doc_versions_hash', table_name='document_versions')
    op.drop_index('ix_doc_versions_doc_status', table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index('ix_messages_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_llm_usage_request_id'), table_name='llm_usage')
    op.drop_index('ix_llm_usage_provider_model', table_name='llm_usage')
    op.drop_index('ix_llm_usage_created', table_name='llm_usage')
    op.drop_index('ix_llm_usage_conversation', table_name='llm_usage')
    op.drop_table('llm_usage')
    op.drop_index('ix_documents_status', table_name='documents')
    op.drop_index('ix_documents_kb_status', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_knowledge_bases_status', table_name='knowledge_bases')
    op.drop_index(op.f('ix_knowledge_bases_slug'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_index('ix_conversations_user_status', table_name='conversations')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index('ix_conversations_user_created', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
